In [2]:
import torch
import torchsummary

import torch 
import torch.nn as nn
from einops import rearrange


# master_encoder = MasterEncoder(max_seq_length=17, embedding_size=8, how_many_basic_encoders=1, num_atten_heads=2)
# # test = torch.rand(1, 17, 16*16*3)
# encoder = BasicEncoder(max_seq_length=17, embedding_size=2*2*3, num_atten_heads=1)
# self_attn = SelfAttention(max_seq_length=17, embedding_size=2*2*3, num_atten_heads=3)
# attn_head = AttentionHead(max_seq_length=17, qkv_size=2*2*3)

creating model...
creating basic encoder...
creating self attention layer...
creating basic encoder...
creating self attention layer...
creating self attention layer...


In [20]:
# print(torchsummary.summary(attn_head, (17, 2*2*3)))
# print(torchsummary.summary(self_attn, (17, 2*2*3)))
# print(torchsummary.summary(encoder, (17, 2*2*3)))
# print(torchsummary.summary(master_encoder, ( 17, 8)))

----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
         LayerNorm-1                [-1, 17, 8]              16
            Linear-2                   [-1, 68]           4,692
            Linear-3                   [-1, 68]           4,692
            Linear-4                   [-1, 68]           4,692
           Softmax-5               [-1, 17, 17]               0
     AttentionHead-6                [-1, 17, 4]               0
            Linear-7                   [-1, 68]           4,692
            Linear-8                   [-1, 68]           4,692
            Linear-9                   [-1, 68]           4,692
          Softmax-10               [-1, 17, 17]               0
    AttentionHead-11                [-1, 17, 4]               0
    SelfAttention-12                [-1, 17, 8]               0
        LayerNorm-13                [-1, 17, 8]              16
           Linear-14                  [

cpu
Finished Training Epoch 1


In [19]:



vit_embeddings.load_state_dict(
    torch.load("test_epoch_1.pth", map_location=torch.device("cpu"))
)
cm, acc = test(vit_embeddings, val_loader, name="test")
print(cm, acc)


# def validation(net, val_dataset) -> Union[list, list]:
#     true_labels = []
#     pred_labels = []
#     net.eval()
#     for i in range(len(val_dataset)):
#         img, label = val_dataset.__getitem__(i)
#         # print(img.shape)
#         true_labels.append(label)
#         output = net(img.unsqueeze(0))
#         output = F.softmax(output, dim=1)
#         output = torch.argmax(output)
#         pred_labels.append(output.item())
#         # break
#     return true_labels, pred_labels


# def validate_and_conf_matrix(net, val_dataset, categories, name="Net") -> None:
#     t, p = validation(net, val_dataset=val_dataset)
#     cm = confusion_matrix(t, p)
#     plt.figure()
#     sns.heatmap(cm, annot=cm, xticklabels=categories, yticklabels=categories, fmt="g")
#     plt.title(f"Confusion matrix for {name}, accuracy={accuracy_score(t, p)}")
#     plt.xlabel("Predicted labels")
#     plt.ylabel("True labels")
#     plt.savefig(f"results/cm_{name}.png")


cpu
(2500,) (2500,)
[[353  86  16  17  28]
 [ 56 310  32  49  53]
 [ 37  80 134  71 178]
 [ 66 120  74  74 166]
 [  7  33  42  14 404]]
[[353  86  16  17  28]
 [ 56 310  32  49  53]
 [ 37  80 134  71 178]
 [ 66 120  74  74 166]
 [  7  33  42  14 404]] <function accuracy_score at 0x7fb0a4514c10>
